version: '3'

services:
  nestjs-app:
    build: ./server/
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    env_file:
      - server/.env

  mysql:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mydb
    volumes:
      - db_data:/var/lib/mysql

  client:
    container_name: client
    build: ./client
    ports:
      - '5173:5173'
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  db_data:

